CREATE DATABASE IF NOT EXISTS ragodb
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE ragodb;

-- 유저(USER)
CREATE TABLE IF NOT EXISTS user (
  user_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  emp_no VARCHAR(11) NOT NULL,
  name VARCHAR(60) NOT NULL,
  dept_id BIGINT NOT NULL, 
  activation BOOLEAN NOT NULL DEFAULT TRUE,
  user_role CHARACTER(1) NOT NULL DEFAULT 'U',
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 부서(DEPARTMENT)
CREATE TABLE IF NOT EXISTS department (
  dept_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 일반 채팅방 메타데이터(GEN_CHAT)
CREATE TABLE IF NOT EXISTS gen_chat (
  gen_chat_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED,
  title VARCHAR(10) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 일반 대화 메시지(GEN_MESSAGE)
CREATE TABLE IF NOT EXISTS gen_message (
  gen_message_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  gen_chat_id BIGINT UNSIGNED NOT NULL,
  sender_type ENUM('U','A') DEFAULT 'U',
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 일반 대화 요약(GEN_CHAT_SUMMARY)
CREATE TABLE IF NOT EXISTS gen_chat_summary (
  gen_sum_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  gen_chat_id BIGINT UNSIGNED NOT NULL,
  summary TEXT NOT NULL,
  message_count INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 일반 대화 업로드 문서(GEN_UPLOAD_FILE)
CREATE TABLE IF NOT EXISTS gen_upload_file (
  gen_file_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  gen_message_id BIGINT UNSIGNED NOT NULL,
  origin_name VARCHAR(255) NOT NULL,
  file_url VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 무역 플로우 메타데이터(TRADE_FLOW)
CREATE TABLE IF NOT EXISTS trade_flow (
  trade_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(60) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 무역 플로우 대화 메시지(DOC_MESSAGE)
CREATE TABLE IF NOT EXISTS doc_message (
  doc_message_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_id BIGINT UNSIGNED NOT NULL,
  sender_type ENUM('U','A') DEFAULT 'U',
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 문서(DOCUMENT)
CREATE TABLE IF NOT EXISTS document (
  doc_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 무역 플로우 요약(TRADE_FLOW_SUMMARY)
CREATE TABLE IF NOT EXISTS trade_flow_summary (
  trade_sum_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_id BIGINT UNSIGNED NOT NULL,
  summary TEXT NOT NULL,
  message_count INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 문서 버전
CREATE TABLE IF NOT EXISTS doc_version (
  version_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  doc_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(60) NOT NULL,
  content TEXT NOT NULL,
  saved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 문서 템플릿
CREATE TABLE IF NOT EXISTS doc_template (
  template_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  template_name VARCHAR(30) NOT NULL UNIQUE,
  content TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



